"""
injector.py — Two responsibilities:

1. Persist a compiled extension's .pyx + .so into a project-local cache dir
   (.speedcraft_cache/) so it survives after the temp build dir is deleted,
   and so re-running the tool doesn't recompile unchanged functions.

2. Generate a small "shim" Python file the user can import from, which
   transparently swaps in the compiled function while keeping a pure-Python
   fallback if the compiled module ever fails to load (e.g. different OS).
"""

from __future__ import annotations

import os
import shutil
from typing import List


CACHE_DIRNAME = ".speedcraft_cache"


def persist_compiled_artifact(build_dir: str, module_glob_prefix: str, project_root: str) -> str:
    """Copies compiled .so/.pyd/.pyx files from a temp build dir into the
    project-local cache directory. Returns the cache directory path."""
    cache_dir = os.path.join(project_root, CACHE_DIRNAME)
    os.makedirs(cache_dir, exist_ok=True)

    for fname in os.listdir(build_dir):
        if fname.startswith(module_glob_prefix):
            shutil.copy2(os.path.join(build_dir, fname), os.path.join(cache_dir, fname))

    return cache_dir


def write_accelerated_shim(
    original_script_path: str,
    accelerated_functions: List[str],
    cache_dir: str,
    module_name_map: dict,
) -> str:
    """
    Writes `<script>_accelerated.py` next to the original script. This file
    imports the original module, then monkey-patches the hot functions with
    their compiled Cython equivalents. If a compiled module fails to import
    (e.g. moved to a different OS/arch without recompiling), it silently
    falls back to the original pure-Python function so the script never
    breaks — it just loses the speedup.
    """
    project_root = os.path.dirname(os.path.abspath(original_script_path))
    script_basename = os.path.splitext(os.path.basename(original_script_path))[0]
    shim_path = os.path.join(project_root, f"{script_basename}_accelerated.py")

    rel_cache_dir = os.path.relpath(cache_dir, project_root)

    lines = [
        '"""',
        f"Auto-generated by SpeedCraft-AI. Import from this file instead of",
        f"'{script_basename}.py' to get the accelerated versions of hot functions.",
        "If a compiled extension can't be loaded on this machine, this file",
        "transparently falls back to the original pure-Python implementation.",
        '"""',
        "import os",
        "import sys",
        "import importlib.util",
        "",
        f"sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))",
        f"import {script_basename} as _original",
        "",
        f'_CACHE_DIR = os.path.join(os.path.dirname(os.path.abspath(__file__)), "{rel_cache_dir}")',
        "",
    ]

    for func_name in accelerated_functions:
        module_name = module_name_map[func_name]
        lines.append(f"# --- {func_name} ---")
        lines.append("try:")
        lines.append(f'    _spec = importlib.util.spec_from_file_location(')
        lines.append(f'        "{module_name}",')
        lines.append(f'        [os.path.join(_CACHE_DIR, f) for f in os.listdir(_CACHE_DIR)')
        lines.append(f'         if f.startswith("{module_name}") and (f.endswith(".so") or f.endswith(".pyd"))][0]')
        lines.append(f'    )')
        lines.append(f'    _mod = importlib.util.module_from_spec(_spec)')
        lines.append(f'    _spec.loader.exec_module(_mod)')
        lines.append(f'    {func_name} = _mod.{func_name}  # compiled, fast')
        lines.append(f'except Exception:')
        lines.append(f'    {func_name} = _original.{func_name}  # fallback, pure python')
        lines.append("")

    lines.append("# Re-export everything else from the original module unchanged")
    lines.append("for _name in dir(_original):")
    lines.append("    if not _name.startswith('_') and _name not in globals():")
    lines.append("        globals()[_name] = getattr(_original, _name)")
    lines.append("")

    content = "\n".join(lines)
    with open(shim_path, "w") as f:
        f.write(content)

    return shim_path
